name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-and-vercel"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build and Deploy Jigsaw Site
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Cache Composer dependencies (PHP vendor directory)
      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php

      # Step 3: Cache Bun dependencies (node_modules directory)
      - name: Cache Bun Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      # Step 4: Setup PHP environment
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      # Step 5: Setup Bun (JavaScript runtime)
      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 6: Install dependencies and build the Jigsaw site
      - name: Build Jigsaw Website
        run: |
          bun install \
          && composer install \
          && bun run prod \
          && ./vendor/bin/jigsaw build production

      # Step 7a: Configure GitHub Pages for deployment
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      # Step 7b: Upload the built site as an artifact for GitHub Pages deployment
      - name: Upload Artifact for GitHub Pages Deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build_production'

      # Step 7c: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Step 8a: Install Vercel CLI for Vercel deployment
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 8b: Deploy to Vercel using CLI and secrets for authentication
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
